FROM node:20 as snip_frontend

ARG AUTH_GOOGLE_ID
ARG AUTH_GOOGLE_SECRET
ARG NEXTAUTH_URL
ARG NEXTAUTH_SECRET

ENV AUTH_GOOGLE_ID ${AUTH_GOOGLE_ID}
ENV AUTH_GOOGLE_SECRET ${AUTH_GOOGLE_SECRET}
ENV NEXTAUTH_URL ${NEXTAUTH_URL}
ENV NEXTAUTH_SECRET ${NEXTAUTH_SECRET}

WORKDIR /app/SnipSavvy_Frontend
COPY . .

RUN npm install
EXPOSE 3000
CMD ["npm", "run", "dev"]




FROM node:20 as snip_backend

ARG MONGO_URL
ARG ENCRYPTION_KEY
ARG ALGORITHM

ENV MONGO_URL ${MONGO_URL}
ENV ENCRYPTION_KEY ${ENCRYPTION_KEY}
ENV ALGORITHM ${ALGORITHM}

WORKDIR /app/SnipSavvy_Backend

RUN git clone https://github.com/SnipSavvy/SnipSavvy_Backend.git .

RUN npm install
EXPOSE 8001
CMD ["npm", "start"]






